var annotated_dup =
[
    [ "Database", "d0/d76/namespace_database.html", [
      [ "Camara", "d0/d36/struct_database_1_1_camara.html", "d0/d36/struct_database_1_1_camara" ],
      [ "Dato", "d4/d34/struct_database_1_1_dato.html", "d4/d34/struct_database_1_1_dato" ],
      [ "Dron", "d5/df8/struct_database_1_1_dron.html", "d5/df8/struct_database_1_1_dron" ],
      [ "Finca", "d5/d30/struct_database_1_1_finca.html", "d5/d30/struct_database_1_1_finca" ],
      [ "HistoricoDatos", "d6/d8c/struct_database_1_1_historico_datos.html", "d6/d8c/struct_database_1_1_historico_datos" ],
      [ "Municipio", "d4/dd7/struct_database_1_1_municipio.html", "d4/dd7/struct_database_1_1_municipio" ],
      [ "Objeto", "d7/d3d/struct_database_1_1_objeto.html", "d7/d3d/struct_database_1_1_objeto" ],
      [ "Provincia", "d2/d70/struct_database_1_1_provincia.html", "d2/d70/struct_database_1_1_provincia" ],
      [ "RelacionDato", "df/dd4/struct_database_1_1_relacion_dato.html", "df/dd4/struct_database_1_1_relacion_dato" ],
      [ "SDO_GEOMETRY", "db/d9a/struct_database_1_1_s_d_o___g_e_o_m_e_t_r_y.html", "db/d9a/struct_database_1_1_s_d_o___g_e_o_m_e_t_r_y" ],
      [ "Sensor", "d2/ded/struct_database_1_1_sensor.html", "d2/ded/struct_database_1_1_sensor" ],
      [ "Vuelo", "dd/d1f/struct_database_1_1_vuelo.html", "dd/d1f/struct_database_1_1_vuelo" ],
      [ "VueloCamara", "db/ddd/struct_database_1_1_vuelo_camara.html", "db/ddd/struct_database_1_1_vuelo_camara" ],
      [ "Zona", "da/d03/struct_database_1_1_zona.html", "da/d03/struct_database_1_1_zona" ]
    ] ],
    [ "GEU", "d0/de1/namespace_g_e_u.html", [
      [ "GuiUtilities", "d3/dd7/namespace_g_e_u_1_1_gui_utilities.html", [
        [ "Colors", "d6/df2/struct_g_e_u_1_1_gui_utilities_1_1_colors.html", null ],
        [ "DragDropIDs", "d3/ddf/struct_g_e_u_1_1_gui_utilities_1_1_drag_drop_i_ds.html", null ],
        [ "ImageTooltipDrawArea", "d9/d92/struct_g_e_u_1_1_gui_utilities_1_1_image_tooltip_draw_area.html", "d9/d92/struct_g_e_u_1_1_gui_utilities_1_1_image_tooltip_draw_area" ],
        [ "Parameters", "d0/d35/struct_g_e_u_1_1_gui_utilities_1_1_parameters.html", null ]
      ] ],
      [ "AmbientLight", "d5/d79/class_g_e_u_1_1_ambient_light.html", null ],
      [ "ApplicationState", "d2/d18/struct_g_e_u_1_1_application_state.html", "d2/d18/struct_g_e_u_1_1_application_state" ],
      [ "BasicAttenuation", "d0/d9a/class_g_e_u_1_1_basic_attenuation.html", "d0/d9a/class_g_e_u_1_1_basic_attenuation" ],
      [ "Camera", "dd/d0c/class_g_e_u_1_1_camera.html", "dd/d0c/class_g_e_u_1_1_camera" ],
      [ "CameraAxisWindow", "d5/da0/class_g_e_u_1_1_camera_axis_window.html", "d5/da0/class_g_e_u_1_1_camera_axis_window" ],
      [ "CameraProjection", "d2/df0/class_g_e_u_1_1_camera_projection.html", "d2/df0/class_g_e_u_1_1_camera_projection" ],
      [ "CloudExportDialogPopup", "d7/dd6/class_g_e_u_1_1_cloud_export_dialog_popup.html", "d7/dd6/class_g_e_u_1_1_cloud_export_dialog_popup" ],
      [ "ComputeShader", "d1/dff/class_g_e_u_1_1_compute_shader.html", "d1/dff/class_g_e_u_1_1_compute_shader" ],
      [ "ConfirmClosePopup", "dd/d90/class_g_e_u_1_1_confirm_close_popup.html", "dd/d90/class_g_e_u_1_1_confirm_close_popup" ],
      [ "ConfirmPopup", "d3/d7c/class_g_e_u_1_1_confirm_popup.html", "d3/d7c/class_g_e_u_1_1_confirm_popup" ],
      [ "DatabaseDownloadedFiles", "d5/df1/struct_g_e_u_1_1_database_downloaded_files.html", "d5/df1/struct_g_e_u_1_1_database_downloaded_files" ],
      [ "DatabaseNewDatoWindow", "d2/d4d/class_g_e_u_1_1_database_new_dato_window.html", "d2/d4d/class_g_e_u_1_1_database_new_dato_window" ],
      [ "DatabaseNewRawPopup", "d2/da0/class_g_e_u_1_1_database_new_raw_popup.html", "d2/da0/class_g_e_u_1_1_database_new_raw_popup" ],
      [ "DatabaseNewVueloPopup", "db/dbe/class_g_e_u_1_1_database_new_vuelo_popup.html", "db/dbe/class_g_e_u_1_1_database_new_vuelo_popup" ],
      [ "DatabaseQueryPopup", "d7/dbe/class_g_e_u_1_1_database_query_popup.html", "d7/dbe/class_g_e_u_1_1_database_query_popup" ],
      [ "DebugWindow", "dc/de7/class_g_e_u_1_1_debug_window.html", "dc/de7/class_g_e_u_1_1_debug_window" ],
      [ "DetailsWindow", "db/d50/class_g_e_u_1_1_details_window.html", "db/d50/class_g_e_u_1_1_details_window" ],
      [ "DirectionalLight", "df/d8b/class_g_e_u_1_1_directional_light.html", null ],
      [ "DistanceAttenuation", "d3/d29/class_g_e_u_1_1_distance_attenuation.html", "d3/d29/class_g_e_u_1_1_distance_attenuation" ],
      [ "FBORender", "d1/de3/class_g_e_u_1_1_f_b_o_render.html", "d1/de3/class_g_e_u_1_1_f_b_o_render" ],
      [ "FBOScreenshot", "d5/d48/class_g_e_u_1_1_f_b_o_screenshot.html", "d5/d48/class_g_e_u_1_1_f_b_o_screenshot" ],
      [ "FileDialogPopup", "d0/d83/class_g_e_u_1_1_file_dialog_popup.html", "d0/d83/class_g_e_u_1_1_file_dialog_popup" ],
      [ "FileManager", "dd/db9/class_g_e_u_1_1_file_manager.html", null ],
      [ "Framebuffer", "da/dd6/class_g_e_u_1_1_framebuffer.html", "da/dd6/class_g_e_u_1_1_framebuffer" ],
      [ "GPUResources", "d2/d21/struct_g_e_u_1_1_g_p_u_resources.html", "d2/d21/struct_g_e_u_1_1_g_p_u_resources" ],
      [ "GUI", "de/de6/class_g_e_u_1_1_g_u_i.html", "de/de6/class_g_e_u_1_1_g_u_i" ],
      [ "I_GUIPopup", "df/ddd/class_g_e_u_1_1_i___g_u_i_popup.html", "df/ddd/class_g_e_u_1_1_i___g_u_i_popup" ],
      [ "I_GUIWindow", "dc/d53/class_g_e_u_1_1_i___g_u_i_window.html", "dc/d53/class_g_e_u_1_1_i___g_u_i_window" ],
      [ "Image", "d8/dc1/class_g_e_u_1_1_image.html", "d8/dc1/class_g_e_u_1_1_image" ],
      [ "ImageTreeSegmentation", "d1/d9a/class_g_e_u_1_1_image_tree_segmentation.html", "d1/d9a/class_g_e_u_1_1_image_tree_segmentation" ],
      [ "InfoPopup", "db/dac/class_g_e_u_1_1_info_popup.html", "db/dac/class_g_e_u_1_1_info_popup" ],
      [ "InputManager", "d9/dad/class_g_e_u_1_1_input_manager.html", "d9/dad/class_g_e_u_1_1_input_manager" ],
      [ "InspectorWindow", "da/d81/class_g_e_u_1_1_inspector_window.html", "da/d81/class_g_e_u_1_1_inspector_window" ],
      [ "InterfaceAdapter", "d8/d88/class_g_e_u_1_1_interface_adapter.html", "d8/d88/class_g_e_u_1_1_interface_adapter" ],
      [ "Light", "db/de3/class_g_e_u_1_1_light.html", "db/de3/class_g_e_u_1_1_light" ],
      [ "LightAttenuation", "d6/dce/class_g_e_u_1_1_light_attenuation.html", "d6/dce/class_g_e_u_1_1_light_attenuation" ],
      [ "LightModel", "d4/dd4/class_g_e_u_1_1_light_model.html", "d4/dd4/class_g_e_u_1_1_light_model" ],
      [ "LightProperties", "d4/d41/class_g_e_u_1_1_light_properties.html", "d4/d41/class_g_e_u_1_1_light_properties" ],
      [ "LinesModel", "d2/d90/class_g_e_u_1_1_lines_model.html", "d2/d90/class_g_e_u_1_1_lines_model" ],
      [ "Material", "d5/def/class_g_e_u_1_1_material.html", "d5/def/class_g_e_u_1_1_material" ],
      [ "MaterialList", "d8/dbd/class_g_e_u_1_1_material_list.html", "d8/dbd/class_g_e_u_1_1_material_list" ],
      [ "MaterialsWindow", "df/df0/class_g_e_u_1_1_materials_window.html", "df/df0/class_g_e_u_1_1_materials_window" ],
      [ "MemoryManager", "dd/d49/class_g_e_u_1_1_memory_manager.html", null ],
      [ "Model3D", "db/d6c/class_g_e_u_1_1_model3_d.html", "db/d6c/class_g_e_u_1_1_model3_d" ],
      [ "ModuleManager", "db/d62/class_g_e_u_1_1_module_manager.html", "db/d62/class_g_e_u_1_1_module_manager" ],
      [ "MultiespectralGUIAdapter", "de/d4a/class_g_e_u_1_1_multiespectral_g_u_i_adapter.html", "de/d4a/class_g_e_u_1_1_multiespectral_g_u_i_adapter" ],
      [ "NASSession", "d2/dfb/class_g_e_u_1_1_n_a_s_session.html", "d2/dfb/class_g_e_u_1_1_n_a_s_session" ],
      [ "OrthographicProjection", "d2/d53/class_g_e_u_1_1_orthographic_projection.html", "d2/d53/class_g_e_u_1_1_orthographic_projection" ],
      [ "PCloudClassifyPopup", "d9/d8f/class_g_e_u_1_1_p_cloud_classify_popup.html", "d9/d8f/class_g_e_u_1_1_p_cloud_classify_popup" ],
      [ "PerspectiveProjection", "d8/de4/class_g_e_u_1_1_perspective_projection.html", "d8/de4/class_g_e_u_1_1_perspective_projection" ],
      [ "PickingWindow", "d9/db1/class_g_e_u_1_1_picking_window.html", "d9/db1/class_g_e_u_1_1_picking_window" ],
      [ "PixarAttenuation", "d5/d6e/class_g_e_u_1_1_pixar_attenuation.html", "d5/d6e/class_g_e_u_1_1_pixar_attenuation" ],
      [ "PointCloud", "d4/dbf/class_g_e_u_1_1_point_cloud.html", "d4/dbf/class_g_e_u_1_1_point_cloud" ],
      [ "PointLight", "d0/d12/class_g_e_u_1_1_point_light.html", null ],
      [ "Renderer", "de/dac/class_g_e_u_1_1_renderer.html", "de/dac/class_g_e_u_1_1_renderer" ],
      [ "RenderingShader", "d0/def/class_g_e_u_1_1_rendering_shader.html", "d0/def/class_g_e_u_1_1_rendering_shader" ],
      [ "ResizeListener", "dc/dda/class_g_e_u_1_1_resize_listener.html", "dc/dda/class_g_e_u_1_1_resize_listener" ],
      [ "RimLight", "d8/dc3/class_g_e_u_1_1_rim_light.html", null ],
      [ "Scene", "d5/d5a/class_g_e_u_1_1_scene.html", "d5/d5a/class_g_e_u_1_1_scene" ],
      [ "ScreenshotListener", "d9/db3/class_g_e_u_1_1_screenshot_listener.html", "d9/db3/class_g_e_u_1_1_screenshot_listener" ],
      [ "SettingsWindow", "da/dc4/class_g_e_u_1_1_settings_window.html", "da/dc4/class_g_e_u_1_1_settings_window" ],
      [ "ShaderEnum", "de/d5b/struct_g_e_u_1_1_shader_enum.html", "de/d5b/struct_g_e_u_1_1_shader_enum" ],
      [ "ShaderManager", "d7/df6/class_g_e_u_1_1_shader_manager.html", "d7/df6/class_g_e_u_1_1_shader_manager" ],
      [ "ShaderProgram", "da/db2/class_g_e_u_1_1_shader_program.html", "da/db2/class_g_e_u_1_1_shader_program" ],
      [ "Singleton", "d1/df9/class_g_e_u_1_1_singleton.html", "d1/df9/class_g_e_u_1_1_singleton" ],
      [ "SpotLight", "df/d9f/class_g_e_u_1_1_spot_light.html", null ],
      [ "StatsWindow", "d0/d9f/class_g_e_u_1_1_stats_window.html", "d0/d9f/class_g_e_u_1_1_stats_window" ],
      [ "Texture", "dc/d36/class_g_e_u_1_1_texture.html", "dc/d36/class_g_e_u_1_1_texture" ],
      [ "ThermalAugment", "d3/d48/class_g_e_u_1_1_thermal_augment.html", "d3/d48/class_g_e_u_1_1_thermal_augment" ],
      [ "ThermalGUIAdapter", "d1/dd3/class_g_e_u_1_1_thermal_g_u_i_adapter.html", "d1/dd3/class_g_e_u_1_1_thermal_g_u_i_adapter" ],
      [ "TriangleMesh", "d9/d4a/class_g_e_u_1_1_triangle_mesh.html", "d9/d4a/class_g_e_u_1_1_triangle_mesh" ],
      [ "VAO", "de/d53/class_g_e_u_1_1_v_a_o.html", "de/d53/class_g_e_u_1_1_v_a_o" ],
      [ "Window", "d8/d78/class_g_e_u_1_1_window.html", "d8/d78/class_g_e_u_1_1_window" ],
      [ "WindowsCommCall", "df/d12/class_g_e_u_1_1_windows_comm_call.html", null ]
    ] ],
    [ "unibn", "de/dd0/namespaceunibn.html", [
      [ "traits", "d2/df4/namespaceunibn_1_1traits.html", [
        [ "access", "dc/d6b/structunibn_1_1traits_1_1access.html", null ],
        [ "access< PointT, 0 >", "dd/d96/structunibn_1_1traits_1_1access_3_01_point_t_00_010_01_4.html", null ],
        [ "access< PointT, 1 >", "d0/d03/structunibn_1_1traits_1_1access_3_01_point_t_00_011_01_4.html", null ],
        [ "access< PointT, 2 >", "db/dfe/structunibn_1_1traits_1_1access_3_01_point_t_00_012_01_4.html", null ]
      ] ],
      [ "L1Distance", "d8/d89/structunibn_1_1_l1_distance.html", null ],
      [ "L2Distance", "de/dc5/structunibn_1_1_l2_distance.html", null ],
      [ "MaxDistance", "d8/df6/structunibn_1_1_max_distance.html", null ],
      [ "Octree", "d2/d9b/classunibn_1_1_octree.html", "d2/d9b/classunibn_1_1_octree" ],
      [ "OctreeParams", "dc/dff/structunibn_1_1_octree_params.html", "dc/dff/structunibn_1_1_octree_params" ]
    ] ],
    [ "AABB", "dc/d47/class_a_a_b_b.html", "dc/d47/class_a_a_b_b" ],
    [ "AutoUpdater", "da/d0b/class_auto_updater.html", "da/d0b/class_auto_updater" ],
    [ "Base64", "d4/d1c/class_base64.html", null ],
    [ "DatabaseConnector", "d1/d09/class_database_connector.html", "d1/d09/class_database_connector" ],
    [ "EnvPath", "dc/df8/struct_env_path.html", null ],
    [ "EnvPointCloud", "d0/d2f/class_env_point_cloud.html", "d0/d2f/class_env_point_cloud" ],
    [ "Histogram", "d5/d2b/class_histogram.html", "d5/d2b/class_histogram" ],
    [ "lazperfPoint", "d9/d47/structlazperf_point.html", "d9/d47/structlazperf_point" ],
    [ "LocaleStrings", "d2/d0c/class_locale_strings.html", "d2/d0c/class_locale_strings" ],
    [ "MetadataReader", "d7/d8f/class_metadata_reader.html", "d7/d8f/class_metadata_reader" ],
    [ "NormalesGUIAdapter", "d4/d3f/class_normales_g_u_i_adapter.html", "d4/d3f/class_normales_g_u_i_adapter" ],
    [ "OpenCVImage", "d0/da8/class_open_c_v_image.html", "d0/da8/class_open_c_v_image" ],
    [ "PointCloudAdaptor", "d3/dcb/struct_point_cloud_adaptor.html", "d3/dcb/struct_point_cloud_adaptor" ],
    [ "Projection", "db/db3/class_projection.html", "db/db3/class_projection" ],
    [ "Rectangle2D", "d0/d10/class_rectangle2_d.html", "d0/d10/class_rectangle2_d" ],
    [ "Reg", "de/d24/struct_reg.html", "de/d24/struct_reg" ],
    [ "Register", "dc/d1a/class_register.html", "dc/d1a/class_register" ],
    [ "str_irradianceList", "d2/d85/structstr__irradiance_list.html", "d2/d85/structstr__irradiance_list" ],
    [ "TextureList", "d2/d7d/class_texture_list.html", "d2/d7d/class_texture_list" ]
];